### ISSUE TITLE
Progress/ Todo

### ISSUE THREAD

**Issue by Noki-Asakuri** [iahacker123/File-sharing#2]
Progress: 

- [x] Login
- [x] Admin/User Dashboard.
- [ ] User config page (Future plan).
- [x] ~Auto remove file after certain amount of time (24h) (Abandonded).~
- [x] Make page load faster. (Optional)
- [ ] Save user config into database (Limit, future user config page?)
- [ ] Write actual README.md?
- [x] Update user info if there is any changes.
